### PR TITLE
Don't use hidden config files.

### PR DESCRIPTION
**Pull request by Metallion**
CI is failing due to unrelated linter errors that are fixed in https://github.com/degica/kaiser/pull/67

The way to usually store config files on *nix systems is to have either a single hidden file in the home directory or a hidden directory with non-hidden files inside.

Kaiser used a hidden directory with hidden files inside which was confusing. I updated it to use the more common hidden directory with non-hidden files pattern.

I've set it up so that kaiser will checked for the hidden files on boot and un-hide them if they exist.

### CODE REVIEW

**Comment by degicat** [comment]
@davidsiaw please review this

**Review by davidsiaw — APPROVED** [review]
LGTM

**Comment by Metallion** [comment]
@davidsiaw It got it in https://github.com/degica/kaiser/pull/67 as mentioned on the top of the PR description. ^_^

**Comment by Metallion** [comment]
@davidsiaw Rubocop has been loved. ^_^

**Review by davidsiaw — APPROVED** [review]
lgtm

**Pull request merged**
