### PR TITLE
fix dns in docker mode

### PR DESCRIPTION
**Pull request by davidsiaw**
fix dns for docker mode

### CODE REVIEW

**Comment by degikko** [comment]
@harsh-dk can you help us review this PR, please?

**Review by harsh-gulhane — DISMISSED** [review]
Finally Working!!!!

**Comment by davidsiaw** [comment]
@harsh-g31 can you please look again i just did a linter fix

**Review by harsh-gulhane — APPROVED** [review]
LGTM. Thank you!!

**Pull request merged**
